"""Added Bios and profile path addition to the users table

Revision ID: 527b87b06a2d
Revises: 70f0504ef6c9
Create Date: 2020-05-11 15:35:08.206147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527b87b06a2d'
down_revision = '70f0504ef6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
