"""Creation of subscription column

Revision ID: b935a4d0cc7a
Revises: c06c74ca3090
Create Date: 2020-05-12 08:00:34.285872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b935a4d0cc7a'
down_revision = 'c06c74ca3090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_subscription'), 'users', ['subscription'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_subscription'), table_name='users')
    op.drop_column('users', 'subscription')
    # ### end Alembic commands ###
